In [1]:
import numpy as np
import pandas as pd
titanic_train = pd.read_csv('titanic-train.csv')

In [2]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
gender          object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [4]:
np.where(titanic_train['Age'].isnull() == True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [5]:
#filtering in pandas

In [6]:
titanic_train.iloc[np.where(titanic_train['Age'].isnull() == True)]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

     gender  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [7]:
titanic_train[titanic_train['Fare'] == titanic_train['Fare'].max()]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [8]:
titanic_train.iloc[np.where(titanic_train['Age'] == 24)]['Name']

89                                Celotti, Mr. Francesco
118                             Baxter, Mr. Quigg Edmond
127                            Madsen, Mr. Fridtjof Arne
139                                   Giglio, Mr. Victor
142    Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...
199               Yrois, Miss. Henriette ("Mrs Harbeck")
210                                       Ali, Mr. Ahmed
234                    Leyson, Mr. Robert William Norman
247                      Hamalainen, Mrs. William (Anna)
293                                  Haas, Miss. Aloisia
294                                     Mineff, Mr. Ivan
310                       Hays, Miss. Margaret Bechstein
316                  Kantor, Mrs. Sinai (Miriam Sternin)
341                       Fortune, Miss. Alice Elizabeth
345                        Brown, Miss. Amelia "Mildred"
369                        Aubart, Mme. Leontine Pauline
394    Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...
437                Richards, Mr

In [9]:
titanic_train[['Age','Cabin']][titanic_train['Cabin'].isnull() == True]

Age Cabin
0    22.0   NaN
2    26.0   NaN
4    35.0   NaN
5     NaN   NaN
7     2.0   NaN
..    ...   ...
884  25.0   NaN
885  39.0   NaN
886  27.0   NaN
888   NaN   NaN
890  32.0   NaN

[687 rows x 2 columns]

In [10]:
titanic_train[titanic_train['Cabin'] == np.nan]['Age']

Series([], Name: Age, dtype: float64)

In [11]:
titanic_train.Name[(titanic_train.gender == 'male') & (titanic_train.Survived == 1)]

17        Williams, Mr. Charles Eugene
21               Beesley, Mr. Lawrence
23        Sloper, Mr. William Thompson
36                    Mamee, Mr. Hanna
55                   Woolner, Mr. Hugh
                    ...               
838                    Chip, Mr. Chang
839               Marechal, Mr. Pierre
857             Daly, Mr. Peter Denis 
869    Johnson, Master. Harold Theodor
889              Behr, Mr. Karl Howell
Name: Name, Length: 109, dtype: object

In [12]:
np.random.seed(23) #seed will not change the random data 
df = pd.DataFrame(np.random.randn(4,5), index = ['a','b','c','d'], columns = ['x','y','z','u','v'])
df

x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [13]:
df.values[df.iloc[:]<0] #values less than 0

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [14]:
df.values[df<0] #values less than 0

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [15]:
d = {'key1' : [1,2,3,4,np.nan], 'key2' : [2,3,np.nan,5,6], 'key3' : [np.nan,np.nan,np.nan,3,8]}
df = pd.DataFrame(d)
df

key1  key2  key3
0   1.0   2.0   NaN
1   2.0   3.0   NaN
2   3.0   NaN   NaN
3   4.0   5.0   3.0
4   NaN   6.0   8.0

In [16]:
di = {'name' : ['sudh','vishal','umang','vishal','umang'], 'mail_id' : ['sudh@gmail.com', 'vishal@gmail.com','umang@gmail.com',
                                                                        'vishal@gmail.com', 'umang@gmail.com'],
      'salary' : [100,200,500,200,500]}
df = pd.DataFrame(di)
df

name           mail_id  salary
0    sudh    sudh@gmail.com     100
1  vishal  vishal@gmail.com     200
2   umang   umang@gmail.com     500
3  vishal  vishal@gmail.com     200
4   umang   umang@gmail.com     500

In [17]:
# df[df.name == 'umang'].describe()
df.groupby('mail_id').describe().loc['umang@gmail.com']

salary  count      2.0
        mean     500.0
        std        0.0
        min      500.0
        25%      500.0
        50%      500.0
        75%      500.0
        max      500.0
Name: umang@gmail.com, dtype: float64

In [18]:
arr1 = np.random.randn(3,4)
arr2 = np.random.randn(3,4)
arr3 = np.random.randn(3,4)

In [19]:
arr1

array([[-0.20184052,  1.04537128,  0.53816197,  0.81211867],
       [ 0.2411063 , -0.95250953, -0.13626676,  1.26724821],
       [ 0.17363364, -1.22325477,  1.41531998,  0.45771098]])

In [20]:
arr2

array([[ 0.72887584,  1.96843473, -0.54778801, -0.67941827],
       [-2.50623032,  0.14696049,  0.60619549, -0.02253889],
       [ 0.01342226,  0.93594489,  0.42062266,  0.41161964]])

In [21]:
arr3

array([[-0.07132392, -0.04543758,  1.04088597, -0.09403473],
       [-0.42084395, -0.55198856, -0.12109755,  0.19014136],
       [ 0.51213739,  0.13153847, -0.33161712, -1.63238628]])

In [22]:
df1 = pd.DataFrame(arr1)
df2 = pd.DataFrame(arr2)
df3 = pd.DataFrame(arr3)

In [23]:
df = pd.concat([df1,df2,df3])
df

0         1         2         3
0 -0.201841  1.045371  0.538162  0.812119
1  0.241106 -0.952510 -0.136267  1.267248
2  0.173634 -1.223255  1.415320  0.457711
0  0.728876  1.968435 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620
0 -0.071324 -0.045438  1.040886 -0.094035
1 -0.420844 -0.551989 -0.121098  0.190141
2  0.512137  0.131538 -0.331617 -1.632386

In [24]:
df.loc[0]

0         1         2         3
0 -0.201841  1.045371  0.538162  0.812119
0  0.728876  1.968435 -0.547788 -0.679418
0 -0.071324 -0.045438  1.040886 -0.094035

In [25]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'gender', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
titanic_train['Cabin'].astype()